def get_distances_map(origin, destination) -> float:

    """
    Função que retorna a distância entre dois locais

    :param origin: string com o nome do local de origem
    :param destination: string com o nome do local de destino
    :return: float com a distância entre os dois locais
    """

    distances = {
        ('Fazenda em Delta - MG', 'Zebu Carnes Ramid Mauad'): 36.7,
        ('Fazenda em Delta - MG', 'Zebu Carnes Saudade'): 39.3,
        ('Fazenda em Delta - MG', 'Zebu Carnes Nossa Senhora do Desterro'): 33.1,
        ('Fazenda em Delta - MG', 'Zebu Carnes Governador Magalhães Pinto'): 33.7,
        ('Fazenda em Delta - MG', 'Zebu Carnes Erick Silva'): 35.1,
        ('Fazenda em Delta - MG', 'Zebu Carnes Carlos Gomes'): 31.8,
        ('Fazenda em Delta - MG', 'Zebu Carnes Conceição das Alagoas'): 32.3,
        ('Fazenda em Delta - MG', 'Zebu Carnes Tônico dos Santos'): 30.4,
        ('Fazenda em Delta - MG', 'Zebu Carnes José Valim de Melo'): 28.1,
        ('Fazenda em Delta - MG', 'Mart Minas Parque Laranjeiras'): 33.1,
        ('Fazenda em Delta - MG', 'Mart Minas Olinda'): 36.8,
        ('Fazenda em Delta - MG', 'Mart Minas Santos Dumont'): 34.9,
        ('Fazenda em Delta - MG', 'Empório Bahamas Praça Uberaba'): 33.5,
        ('Fazenda em Delta - MG', 'Bahamas Mix Nossa Senhora do Desterro'): 37,
        ('Fazenda em Delta - MG', 'Bahamas Mix Santana Borges'): 37.6,
        ('Fazenda em Delta - MG', 'Bahamas Mix Cherem'): 28.3,
        ('Fazenda em Delta - MG', 'Bahamas Express Leopoldino'): 32.2,
        ('Fazenda em Delta - MG', 'Atacadão - Santos Dumont'): 33.7,
        ('Fazenda em Delta - MG', 'ABC Atacado e Varejo Cherém'): 29.9,
        ('Fazenda em Delta - MG', 'Supermercado ABC - Rua João Alfredo'): 30.4,
        ('Fazenda em Delta - MG', 'Villefort'): 32.2,
        ('Zebu Carnes Ramid Mauad', 'Fazenda em Delta - MG'): 36.7,
        ('Zebu Carnes Ramid Mauad', 'Zebu Carnes Saudade'): 4.9,
        ('Zebu Carnes Ramid Mauad', 'Zebu Carnes Nossa Senhora do Desterro'): 14.6,
        ('Zebu Carnes Ramid Mauad', 'Zebu Carnes Governador Magalhães Pinto'): 7.3,
        ('Zebu Carnes Ramid Mauad', 'Zebu Carnes Erick Silva'): 10.2,
        ('Zebu Carnes Ramid Mauad', 'Zebu Carnes Carlos Gomes'): 8.6,
        ('Zebu Carnes Ramid Mauad', 'Zebu Carnes Conceição das Alagoas'): 7.3,
        ('Zebu Carnes Ramid Mauad', 'Zebu Carnes Tônico dos Santos'): 7.4,
        ('Zebu Carnes Ramid Mauad', 'Zebu Carnes José Valim de Melo'): 10.2,
        ('Zebu Carnes Ramid Mauad', 'Mart Minas Parque Laranjeiras'): 5.1,
        ('Zebu Carnes Ramid Mauad', 'Mart Minas Olinda'): 2.4,
        ('Zebu Carnes Ramid Mauad', 'Mart Minas Santos Dumont'): 5.8,
        ('Zebu Carnes Ramid Mauad', 'Empório Bahamas Praça Uberaba'): 7,
        ('Zebu Carnes Ramid Mauad', 'Bahamas Mix Nossa Senhora do Desterro'): 15.7,
        ('Zebu Carnes Ramid Mauad', 'Bahamas Mix Santana Borges'): 3.2,
        ('Zebu Carnes Ramid Mauad', 'Bahamas Mix Cherem'): 9.9,
        ('Zebu Carnes Ramid Mauad', 'Bahamas Express Leopoldino'): 7.1,
        ('Zebu Carnes Ramid Mauad', 'Atacadão - Santos Dumont'): 6.3,
        ('Zebu Carnes Ramid Mauad', 'ABC Atacado e Varejo Cherém'): 8.6,
        ('Zebu Carnes Ramid Mauad', 'Supermercado ABC - Rua João Alfredo'): 8.9,
        ('Zebu Carnes Ramid Mauad', 'Villefort'): 6.6,
        ('Zebu Carnes Saudade', 'Fazenda em Delta - MG'): 39.3,
        ('Zebu Carnes Saudade', 'Zebu Carnes Ramid Mauad'): 4.9,
        ('Zebu Carnes Saudade', 'Zebu Carnes Nossa Senhora do Desterro'): 8.1,
        ('Zebu Carnes Saudade', 'Zebu Carnes Governador Magalhães Pinto'): 3.1,
        ('Zebu Carnes Saudade', 'Zebu Carnes Erick Silva'): 6,
        ('Zebu Carnes Saudade', 'Zebu Carnes Carlos Gomes'): 4.3,
        ('Zebu Carnes Saudade', 'Zebu Carnes Conceição das Alagoas'): 2.9,
        ('Zebu Carnes Saudade', 'Zebu Carnes Tônico dos Santos'): 5.6,
        ('Zebu Carnes Saudade', 'Zebu Carnes José Valim de Melo'): 13.4,
        ('Zebu Carnes Saudade', 'Mart Minas Parque Laranjeiras'): 8.2,
        ('Zebu Carnes Saudade', 'Mart Minas Olinda'): 2.5,
        ('Zebu Carnes Saudade', 'Mart Minas Santos Dumont'): 3,
        ('Zebu Carnes Saudade', 'Empório Bahamas Praça Uberaba'): 2.9,
        ('Zebu Carnes Saudade', 'Bahamas Mix Nossa Senhora do Desterro'): 8.7,
        ('Zebu Carnes Saudade', 'Bahamas Mix Santana Borges'): 1.9,
        ('Zebu Carnes Saudade', 'Bahamas Mix Cherem'): 7.8,
        ('Zebu Carnes Saudade', 'Bahamas Express Leopoldino'): 2.9,
        ('Zebu Carnes Saudade', 'Atacadão - Santos Dumont'): 3.5,
        ('Zebu Carnes Saudade', 'ABC Atacado e Varejo Cherém'): 6.4,
        ('Zebu Carnes Saudade', 'Supermercado ABC - Rua João Alfredo'): 4.7,
        ('Zebu Carnes Saudade', 'Villefort'): 3.7,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Fazenda em Delta - MG'): 33.1,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Zebu Carnes Ramid Mauad'): 14.6,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Zebu Carnes Saudade'): 8.1,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Zebu Carnes Governador Magalhães Pinto'): 6.3,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Zebu Carnes Erick Silva'): 4.7,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Zebu Carnes Carlos Gomes'): 4.1,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Zebu Carnes Conceição das Alagoas'): 5.7,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Zebu Carnes Tônico dos Santos'): 6.3,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Zebu Carnes José Valim de Melo'): 4.5,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Mart Minas Parque Laranjeiras'): 11.1,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Mart Minas Olinda'): 14.8,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Mart Minas Santos Dumont'): 7.4,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Empório Bahamas Praça Uberaba'): 6.2,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Bahamas Mix Nossa Senhora do Desterro'): 2,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Bahamas Mix Santana Borges'): 9.3,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Bahamas Mix Cherem'): 6.2,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Bahamas Express Leopoldino'): 4.9,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Atacadão - Santos Dumont'): 6.8,
        ('Zebu Carnes Nossa Senhora do Desterro', 'ABC Atacado e Varejo Cherém'): 5.5,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Supermercado ABC - Rua João Alfredo'): 3,
        ('Zebu Carnes Nossa Senhora do Desterro', 'Villefort'): 7.6,
        ('Zebu Carnes Governador Magalhães Pinto', 'Fazenda em Delta - MG'): 33.7,
        ('Zebu Carnes Governador Magalhães Pinto', 'Zebu Carnes Ramid Mauad'): 7.3,
        ('Zebu Carnes Governador Magalhães Pinto', 'Zebu Carnes Saudade'): 3.1,
        ('Zebu Carnes Governador Magalhães Pinto', 'Zebu Carnes Nossa Senhora do Desterro'): 6.3,
        ('Zebu Carnes Governador Magalhães Pinto', 'Zebu Carnes Erick Silva'): 3.2,
        ('Zebu Carnes Governador Magalhães Pinto', 'Zebu Carnes Carlos Gomes'): 2.5,
        ('Zebu Carnes Governador Magalhães Pinto', 'Zebu Carnes Conceição das Alagoas'): 3.8,
        ('Zebu Carnes Governador Magalhães Pinto', 'Zebu Carnes Tônico dos Santos'): 6,
        ('Zebu Carnes Governador Magalhães Pinto', 'Zebu Carnes José Valim de Melo'): 7.3,
        ('Zebu Carnes Governador Magalhães Pinto', 'Mart Minas Parque Laranjeiras'): 11.1,
        ('Zebu Carnes Governador Magalhães Pinto', 'Mart Minas Olinda'): 5.4,
        ('Zebu Carnes Governador Magalhães Pinto', 'Mart Minas Santos Dumont'): 4.2,
        ('Zebu Carnes Governador Magalhães Pinto', 'Empório Bahamas Praça Uberaba'): 1.3,
        ('Zebu Carnes Governador Magalhães Pinto', 'Bahamas Mix Nossa Senhora do Desterro'): 5.8,
        ('Zebu Carnes Governador Magalhães Pinto', 'Bahamas Mix Santana Borges'): 4.8,
        ('Zebu Carnes Governador Magalhães Pinto', 'Bahamas Mix Cherem'): 6.4,
        ('Zebu Carnes Governador Magalhães Pinto', 'Bahamas Express Leopoldino'): 2.1,
        ('Zebu Carnes Governador Magalhães Pinto', 'Atacadão - Santos Dumont'): 3.5,
        ('Zebu Carnes Governador Magalhães Pinto', 'ABC Atacado e Varejo Cherém'): 5.8,
        ('Zebu Carnes Governador Magalhães Pinto', 'Supermercado ABC - Rua João Alfredo'): 3.9,
        ('Zebu Carnes Governador Magalhães Pinto', 'Villefort'): 4.4,
        ('Zebu Carnes Erick Silva', 'Fazenda em Delta - MG'): 35.1,
        ('Zebu Carnes Erick Silva', 'Zebu Carnes Ramid Mauad'): 10.2,
        ('Zebu Carnes Erick Silva', 'Zebu Carnes Saudade'): 6,
        ('Zebu Carnes Erick Silva', 'Zebu Carnes Nossa Senhora do Desterro'): 4.7,
        ('Zebu Carnes Erick Silva', 'Zebu Carnes Governador Magalhães Pinto'): 3.2,
        ('Zebu Carnes Erick Silva', 'Zebu Carnes Carlos Gomes'): 3.8,
        ('Zebu Carnes Erick Silva', 'Zebu Carnes Conceição das Alagoas'): 5.9,
        ('Zebu Carnes Erick Silva', 'Zebu Carnes Tônico dos Santos'): 7.3,
        ('Zebu Carnes Erick Silva', 'Zebu Carnes José Valim de Melo'): 7.9,
        ('Zebu Carnes Erick Silva', 'Mart Minas Parque Laranjeiras'): 10,
        ('Zebu Carnes Erick Silva', 'Mart Minas Olinda'): 8.2,
        ('Zebu Carnes Erick Silva', 'Mart Minas Santos Dumont'): 6,
        ('Zebu Carnes Erick Silva', 'Empório Bahamas Praça Uberaba'): 5.1,
        ('Zebu Carnes Erick Silva', 'Bahamas Mix Nossa Senhora do Desterro'): 4.5,
        ('Zebu Carnes Erick Silva', 'Bahamas Mix Santana Borges'): 7.7,
        ('Zebu Carnes Erick Silva', 'Bahamas Mix Cherem'): 7.7,
        ('Zebu Carnes Erick Silva', 'Bahamas Express Leopoldino'): 3.4,
        ('Zebu Carnes Erick Silva', 'Atacadão - Santos Dumont'): 5.3,
        ('Zebu Carnes Erick Silva', 'ABC Atacado e Varejo Cherém'): 7.1,
        ('Zebu Carnes Erick Silva', 'Supermercado ABC - Rua João Alfredo'): 4.3,
        ('Zebu Carnes Erick Silva', 'Villefort'): 6.2,
        ('Zebu Carnes Carlos Gomes', 'Fazenda em Delta - MG'): 31.8,
        ('Zebu Carnes Carlos Gomes', 'Zebu Carnes Ramid Mauad'): 8.6,
        ('Zebu Carnes Carlos Gomes', 'Zebu Carnes Saudade'): 4.3,
        ('Zebu Carnes Carlos Gomes', 'Zebu Carnes Nossa Senhora do Desterro'): 4.1,
        ('Zebu Carnes Carlos Gomes', 'Zebu Carnes Governador Magalhães Pinto'): 2.5,
        ('Zebu Carnes Carlos Gomes', 'Zebu Carnes Erick Silva'): 3.8,
        ('Zebu Carnes Carlos Gomes', 'Zebu Carnes Conceição das Alagoas'): 3.5,
        ('Zebu Carnes Carlos Gomes', 'Zebu Carnes Tônico dos Santos'): 4.8,
        ('Zebu Carnes Carlos Gomes', 'Zebu Carnes José Valim de Melo'): 4.6,
        ('Zebu Carnes Carlos Gomes', 'Mart Minas Parque Laranjeiras'): 8.3,
        ('Zebu Carnes Carlos Gomes', 'Mart Minas Olinda'): 7,
        ('Zebu Carnes Carlos Gomes', 'Mart Minas Santos Dumont'): 3.8,
        ('Zebu Carnes Carlos Gomes', 'Empório Bahamas Praça Uberaba'): 2.9,
        ('Zebu Carnes Carlos Gomes', 'Bahamas Mix Nossa Senhora do Desterro'): 4.7,
        ('Zebu Carnes Carlos Gomes', 'Bahamas Mix Santana Borges'): 6.4,
        ('Zebu Carnes Carlos Gomes', 'Bahamas Mix Cherem'): 4.2,
        ('Zebu Carnes Carlos Gomes', 'Bahamas Express Leopoldino'): 1.7,
        ('Zebu Carnes Carlos Gomes', 'Atacadão - Santos Dumont'): 3.6,
        ('Zebu Carnes Carlos Gomes', 'ABC Atacado e Varejo Cherém'): 4.7,
        ('Zebu Carnes Carlos Gomes', 'Supermercado ABC - Rua João Alfredo'): 1.2,
        ('Zebu Carnes Carlos Gomes', 'Villefort'): 4.1,
        ('Zebu Carnes Conceição das Alagoas', 'Fazenda em Delta - MG'): 32.3,
        ('Zebu Carnes Conceição das Alagoas', 'Zebu Carnes Ramid Mauad'): 7.3,
        ('Zebu Carnes Conceição das Alagoas', 'Zebu Carnes Saudade'): 2.9,
        ('Zebu Carnes Conceição das Alagoas', 'Zebu Carnes Nossa Senhora do Desterro'): 5.7,
        ('Zebu Carnes Conceição das Alagoas', 'Zebu Carnes Governador Magalhães Pinto'): 3.8,
        ('Zebu Carnes Conceição das Alagoas', 'Zebu Carnes Erick Silva'): 5.9,
        ('Zebu Carnes Conceição das Alagoas', 'Zebu Carnes Carlos Gomes'): 3.5,
        ('Zebu Carnes Conceição das Alagoas', 'Zebu Carnes Tônico dos Santos'): 2.2,
        ('Zebu Carnes Conceição das Alagoas', 'Zebu Carnes José Valim de Melo'): 4.3,
        ('Zebu Carnes Conceição das Alagoas', 'Mart Minas Parque Laranjeiras'): 5,
        ('Zebu Carnes Conceição das Alagoas', 'Mart Minas Olinda'): 5,
        ('Zebu Carnes Conceição das Alagoas', 'Mart Minas Santos Dumont'): 1.3,
        ('Zebu Carnes Conceição das Alagoas', 'Empório Bahamas Praça Uberaba'): 3.1,
        ('Zebu Carnes Conceição das Alagoas', 'Bahamas Mix Nossa Senhora do Desterro'): 7.8,
        ('Zebu Carnes Conceição das Alagoas', 'Bahamas Mix Santana Borges'): 4.4,
        ('Zebu Carnes Conceição das Alagoas', 'Bahamas Mix Cherem'): 3.5,
        ('Zebu Carnes Conceição das Alagoas', 'Bahamas Express Leopoldino'): 1.5,
        ('Zebu Carnes Conceição das Alagoas', 'Atacadão - Santos Dumont'): 1.6,
        ('Zebu Carnes Conceição das Alagoas', 'ABC Atacado e Varejo Cherém'): 2.9,
        ('Zebu Carnes Conceição das Alagoas', 'Supermercado ABC - Rua João Alfredo'): 3,
        ('Zebu Carnes Conceição das Alagoas', 'Villefort'): 1.3,
        ('Zebu Carnes Tônico dos Santos', 'Fazenda em Delta - MG'): 30.4,
        ('Zebu Carnes Tônico dos Santos', 'Zebu Carnes Ramid Mauad'): 7.4,
        ('Zebu Carnes Tônico dos Santos', 'Zebu Carnes Saudade'): 5.6,
        ('Zebu Carnes Tônico dos Santos', 'Zebu Carnes Nossa Senhora do Desterro'): 6.3,
        ('Zebu Carnes Tônico dos Santos', 'Zebu Carnes Governador Magalhães Pinto'): 6,
        ('Zebu Carnes Tônico dos Santos', 'Zebu Carnes Erick Silva'): 7.3,
        ('Zebu Carnes Tônico dos Santos', 'Zebu Carnes Carlos Gomes'): 4.8,
        ('Zebu Carnes Tônico dos Santos', 'Zebu Carnes Conceição das Alagoas'): 2.2,
        ('Zebu Carnes Tônico dos Santos', 'Zebu Carnes José Valim de Melo'): 4.3,
        ('Zebu Carnes Tônico dos Santos', 'Mart Minas Parque Laranjeiras'): 4.1,
        ('Zebu Carnes Tônico dos Santos', 'Mart Minas Olinda'): 8,
        ('Zebu Carnes Tônico dos Santos', 'Mart Minas Santos Dumont'): 3.4,
        ('Zebu Carnes Tônico dos Santos', 'Empório Bahamas Praça Uberaba'): 5.5,
        ('Zebu Carnes Tônico dos Santos', 'Bahamas Mix Nossa Senhora do Desterro'): 8,
        ('Zebu Carnes Tônico dos Santos', 'Bahamas Mix Santana Borges'): 5.5,
        ('Zebu Carnes Tônico dos Santos', 'Bahamas Mix Cherem'): 2.9,
        ('Zebu Carnes Tônico dos Santos', 'Bahamas Express Leopoldino'): 3.3,
        ('Zebu Carnes Tônico dos Santos', 'Atacadão - Santos Dumont'): 3.3,
        ('Zebu Carnes Tônico dos Santos', 'ABC Atacado e Varejo Cherém'): 1.5,
        ('Zebu Carnes Tônico dos Santos', 'Supermercado ABC - Rua João Alfredo'): 4.6,
        ('Zebu Carnes Tônico dos Santos', 'Villefort'): 1.7,
        ('Zebu Carnes José Valim de Melo', 'Fazenda em Delta - MG'): 28.1,
        ('Zebu Carnes José Valim de Melo', 'Zebu Carnes Ramid Mauad'): 10.2,
        ('Zebu Carnes José Valim de Melo', 'Zebu Carnes Saudade'): 13.4,
        ('Zebu Carnes José Valim de Melo', 'Zebu Carnes Nossa Senhora do Desterro'): 4.5,
        ('Zebu Carnes José Valim de Melo', 'Zebu Carnes Governador Magalhães Pinto'): 7.3,
        ('Zebu Carnes José Valim de Melo', 'Zebu Carnes Erick Silva'): 7.9,
        ('Zebu Carnes José Valim de Melo', 'Zebu Carnes Carlos Gomes'): 4.6,
        ('Zebu Carnes José Valim de Melo', 'Zebu Carnes Conceição das Alagoas'): 4.3,
        ('Zebu Carnes José Valim de Melo', 'Zebu Carnes Tônico dos Santos'): 4.3,
        ('Zebu Carnes José Valim de Melo', 'Mart Minas Parque Laranjeiras'): 6.9,
        ('Zebu Carnes José Valim de Melo', 'Mart Minas Olinda'): 10.6,
        ('Zebu Carnes José Valim de Melo', 'Mart Minas Santos Dumont'): 5.8,
        ('Zebu Carnes José Valim de Melo', 'Empório Bahamas Praça Uberaba'): 6.9,
        ('Zebu Carnes José Valim de Melo', 'Bahamas Mix Nossa Senhora do Desterro'): 7.1,
        ('Zebu Carnes José Valim de Melo', 'Bahamas Mix Santana Borges'): 11.4,
        ('Zebu Carnes José Valim de Melo', 'Bahamas Mix Cherem'): 2.1,
        ('Zebu Carnes José Valim de Melo', 'Bahamas Express Leopoldino'): 5.6,
        ('Zebu Carnes José Valim de Melo', 'Atacadão - Santos Dumont'): 6.5,
        ('Zebu Carnes José Valim de Melo', 'ABC Atacado e Varejo Cherém'): 3,
        ('Zebu Carnes José Valim de Melo', 'Supermercado ABC - Rua João Alfredo'): 3.8,
        ('Zebu Carnes José Valim de Melo', 'Villefort'): 5,
        ('Mart Minas Parque Laranjeiras', 'Fazenda em Delta - MG'): 33.1,
        ('Mart Minas Parque Laranjeiras', 'Zebu Carnes Ramid Mauad'): 5.1,
        ('Mart Minas Parque Laranjeiras', 'Zebu Carnes Saudade'): 8.2,
        ('Mart Minas Parque Laranjeiras', 'Zebu Carnes Nossa Senhora do Desterro'): 11.1,
        ('Mart Minas Parque Laranjeiras', 'Zebu Carnes Governador Magalhães Pinto'): 11.1,
        ('Mart Minas Parque Laranjeiras', 'Zebu Carnes Erick Silva'): 10,
        ('Mart Minas Parque Laranjeiras', 'Zebu Carnes Carlos Gomes'): 8.3,
        ('Mart Minas Parque Laranjeiras', 'Zebu Carnes Conceição das Alagoas'): 5,
        ('Mart Minas Parque Laranjeiras', 'Zebu Carnes Tônico dos Santos'): 4.1,
        ('Mart Minas Parque Laranjeiras', 'Zebu Carnes José Valim de Melo'): 6.9,
        ('Mart Minas Parque Laranjeiras', 'Mart Minas Olinda'): 4.8,
        ('Mart Minas Parque Laranjeiras', 'Mart Minas Santos Dumont'): 5.4,
        ('Mart Minas Parque Laranjeiras', 'Empório Bahamas Praça Uberaba'): 7.5,
        ('Mart Minas Parque Laranjeiras', 'Bahamas Mix Nossa Senhora do Desterro'): 12.6,
        ('Mart Minas Parque Laranjeiras', 'Bahamas Mix Santana Borges'): 5.6,
        ('Mart Minas Parque Laranjeiras', 'Bahamas Mix Cherem'): 6.8,
        ('Mart Minas Parque Laranjeiras', 'Bahamas Express Leopoldino'): 6.5,
        ('Mart Minas Parque Laranjeiras', 'Atacadão - Santos Dumont'): 5.4,
        ('Mart Minas Parque Laranjeiras', 'ABC Atacado e Varejo Cherém'): 5.5,
        ('Mart Minas Parque Laranjeiras', 'Supermercado ABC - Rua João Alfredo'): 9,
        ('Mart Minas Parque Laranjeiras', 'Villefort'): 4.1,
        ('Mart Minas Olinda', 'Fazenda em Delta - MG'): 36.8,
        ('Mart Minas Olinda', 'Zebu Carnes Ramid Mauad'): 2.4,
        ('Mart Minas Olinda', 'Zebu Carnes Saudade'): 2.5,
        ('Mart Minas Olinda', 'Zebu Carnes Nossa Senhora do Desterro'): 14.8,
        ('Mart Minas Olinda', 'Zebu Carnes Governador Magalhães Pinto'): 5.4,
        ('Mart Minas Olinda', 'Zebu Carnes Erick Silva'): 8.2,
        ('Mart Minas Olinda', 'Zebu Carnes Carlos Gomes'): 7,
        ('Mart Minas Olinda', 'Zebu Carnes Conceição das Alagoas'): 5,
        ('Mart Minas Olinda', 'Zebu Carnes Tônico dos Santos'): 8,
        ('Mart Minas Olinda', 'Zebu Carnes José Valim de Melo'): 10.6,
        ('Mart Minas Olinda', 'Mart Minas Parque Laranjeiras'): 4.8,
        ('Mart Minas Olinda', 'Mart Minas Santos Dumont'): 3.2,
        ('Mart Minas Olinda', 'Empório Bahamas Praça Uberaba'): 4.6,
        ('Mart Minas Olinda', 'Bahamas Mix Nossa Senhora do Desterro'): 10.3,
        ('Mart Minas Olinda', 'Bahamas Mix Santana Borges'): 0.8,
        ('Mart Minas Olinda', 'Bahamas Mix Cherem'): 6.8,
        ('Mart Minas Olinda', 'Bahamas Express Leopoldino'): 4.7,
        ('Mart Minas Olinda', 'Atacadão - Santos Dumont'): 3.7,
        ('Mart Minas Olinda', 'ABC Atacado e Varejo Cherém'): 5.5,
        ('Mart Minas Olinda', 'Supermercado ABC - Rua João Alfredo'): 6.5,
        ('Mart Minas Olinda', 'Villefort'): 3.3,
        ('Mart Minas Santos Dumont', 'Fazenda em Delta - MG'): 34.9,
        ('Mart Minas Santos Dumont', 'Zebu Carnes Ramid Mauad'): 5.8,
        ('Mart Minas Santos Dumont', 'Zebu Carnes Saudade'): 3,
        ('Mart Minas Santos Dumont', 'Zebu Carnes Nossa Senhora do Desterro'): 7.4,
        ('Mart Minas Santos Dumont', 'Zebu Carnes Governador Magalhães Pinto'): 4.2,
        ('Mart Minas Santos Dumont', 'Zebu Carnes Erick Silva'): 6,
        ('Mart Minas Santos Dumont', 'Zebu Carnes Carlos Gomes'): 3.8,
        ('Mart Minas Santos Dumont', 'Zebu Carnes Conceição das Alagoas'): 1.3,
        ('Mart Minas Santos Dumont', 'Zebu Carnes Tônico dos Santos'): 3.4,
        ('Mart Minas Santos Dumont', 'Zebu Carnes José Valim de Melo'): 5.8,
        ('Mart Minas Santos Dumont', 'Mart Minas Parque Laranjeiras'): 5.4,
        ('Mart Minas Santos Dumont', 'Mart Minas Olinda'): 3.2,
        ('Mart Minas Santos Dumont', 'Empório Bahamas Praça Uberaba'): 2.9,
        ('Mart Minas Santos Dumont', 'Bahamas Mix Nossa Senhora do Desterro'): 7.6,
        ('Mart Minas Santos Dumont', 'Bahamas Mix Santana Borges'): 3.6,
        ('Mart Minas Santos Dumont', 'Bahamas Mix Cherem'): 5,
        ('Mart Minas Santos Dumont', 'Bahamas Express Leopoldino'): 1.9,
        ('Mart Minas Santos Dumont', 'Atacadão - Santos Dumont'): 0.8,
        ('Mart Minas Santos Dumont', 'ABC Atacado e Varejo Cherém'): 3.6,
        ('Mart Minas Santos Dumont', 'Supermercado ABC - Rua João Alfredo'): 3.7,
        ('Mart Minas Santos Dumont', 'Villefort'): 1.3,
        ('Empório Bahamas Praça Uberaba', 'Fazenda em Delta - MG'): 33.5,
        ('Empório Bahamas Praça Uberaba', 'Zebu Carnes Ramid Mauad'): 7,
        ('Empório Bahamas Praça Uberaba', 'Zebu Carnes Saudade'): 2.9,
        ('Empório Bahamas Praça Uberaba', 'Zebu Carnes Nossa Senhora do Desterro'): 6.2,
        ('Empório Bahamas Praça Uberaba', 'Zebu Carnes Governador Magalhães Pinto'): 1.3,
        ('Empório Bahamas Praça Uberaba', 'Zebu Carnes Erick Silva'): 5.1,
        ('Empório Bahamas Praça Uberaba', 'Zebu Carnes Carlos Gomes'): 2.9,
        ('Empório Bahamas Praça Uberaba', 'Zebu Carnes Conceição das Alagoas'): 3.1,
        ('Empório Bahamas Praça Uberaba', 'Zebu Carnes Tônico dos Santos'): 5.5,
        ('Empório Bahamas Praça Uberaba', 'Zebu Carnes José Valim de Melo'): 6.9,
        ('Empório Bahamas Praça Uberaba', 'Mart Minas Parque Laranjeiras'): 7.5,
        ('Empório Bahamas Praça Uberaba', 'Mart Minas Olinda'): 4.6,
        ('Empório Bahamas Praça Uberaba', 'Mart Minas Santos Dumont'): 2.9,
        ('Empório Bahamas Praça Uberaba', 'Bahamas Mix Nossa Senhora do Desterro'): 7.1,
        ('Empório Bahamas Praça Uberaba', 'Bahamas Mix Santana Borges'): 4.4,
        ('Empório Bahamas Praça Uberaba', 'Bahamas Mix Cherem'): 6,
        ('Empório Bahamas Praça Uberaba', 'Bahamas Express Leopoldino'): 1.8,
        ('Empório Bahamas Praça Uberaba', 'Atacadão - Santos Dumont'): 3,
        ('Empório Bahamas Praça Uberaba', 'ABC Atacado e Varejo Cherém'): 5.5,
        ('Empório Bahamas Praça Uberaba', 'Supermercado ABC - Rua João Alfredo'): 3.6,
        ('Empório Bahamas Praça Uberaba', 'Villefort'): 4,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Fazenda em Delta - MG'): 37,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Zebu Carnes Ramid Mauad'): 15.7,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Zebu Carnes Saudade'): 8.7,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Zebu Carnes Nossa Senhora do Desterro'): 2,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Zebu Carnes Governador Magalhães Pinto'): 5.8,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Zebu Carnes Erick Silva'): 4.5,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Zebu Carnes Carlos Gomes'): 4.7,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Zebu Carnes Conceição das Alagoas'): 7.8,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Zebu Carnes Tônico dos Santos'): 8,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Zebu Carnes José Valim de Melo'): 7.1,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Mart Minas Parque Laranjeiras'): 12.6,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Mart Minas Olinda'): 10.3,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Mart Minas Santos Dumont'): 7.6,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Empório Bahamas Praça Uberaba'): 7.1,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Bahamas Mix Santana Borges'): 10.4,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Bahamas Mix Cherem'): 7.1,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Bahamas Express Leopoldino'): 5.9,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Atacadão - Santos Dumont'): 7.8,
        ('Bahamas Mix Nossa Senhora do Desterro', 'ABC Atacado e Varejo Cherém'): 6.5,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Supermercado ABC - Rua João Alfredo'): 4.1,
        ('Bahamas Mix Nossa Senhora do Desterro', 'Villefort'): 7.9,
        ('Bahamas Mix Santana Borges', 'Fazenda em Delta - MG'): 37.6,
        ('Bahamas Mix Santana Borges', 'Zebu Carnes Ramid Mauad'): 3.2,
        ('Bahamas Mix Santana Borges', 'Zebu Carnes Saudade'): 1.9,
        ('Bahamas Mix Santana Borges', 'Zebu Carnes Nossa Senhora do Desterro'): 9.3,
        ('Bahamas Mix Santana Borges', 'Zebu Carnes Governador Magalhães Pinto'): 4.8,
        ('Bahamas Mix Santana Borges', 'Zebu Carnes Erick Silva'): 7.7,
        ('Bahamas Mix Santana Borges', 'Zebu Carnes Carlos Gomes'): 6.4,
        ('Bahamas Mix Santana Borges', 'Zebu Carnes Conceição das Alagoas'): 4.4,
        ('Bahamas Mix Santana Borges', 'Zebu Carnes Tônico dos Santos'): 5.5,
        ('Bahamas Mix Santana Borges', 'Zebu Carnes José Valim de Melo'): 11.4,
        ('Bahamas Mix Santana Borges', 'Mart Minas Parque Laranjeiras'): 5.6,
        ('Bahamas Mix Santana Borges', 'Mart Minas Olinda'): 0.8,
        ('Bahamas Mix Santana Borges', 'Mart Minas Santos Dumont'): 3.6,
        ('Bahamas Mix Santana Borges', 'Empório Bahamas Praça Uberaba'): 4.4,
        ('Bahamas Mix Santana Borges', 'Bahamas Mix Nossa Senhora do Desterro'): 10.4,
        ('Bahamas Mix Santana Borges', 'Bahamas Mix Cherem'): 11.3,
        ('Bahamas Mix Santana Borges', 'Bahamas Express Leopoldino'): 5.4,
        ('Bahamas Mix Santana Borges', 'Atacadão - Santos Dumont'): 4.7,
        ('Bahamas Mix Santana Borges', 'ABC Atacado e Varejo Cherém'): 6.2,
        ('Bahamas Mix Santana Borges', 'Supermercado ABC - Rua João Alfredo'): 7.2,
        ('Bahamas Mix Santana Borges', 'Villefort'): 4.1,
        ('Bahamas Mix Cherem', 'Fazenda em Delta - MG'): 28.3,
        ('Bahamas Mix Cherem', 'Zebu Carnes Ramid Mauad'): 9.9,
        ('Bahamas Mix Cherem', 'Zebu Carnes Saudade'): 7.8,
        ('Bahamas Mix Cherem', 'Zebu Carnes Nossa Senhora do Desterro'): 6.2,
        ('Bahamas Mix Cherem', 'Zebu Carnes Governador Magalhães Pinto'): 6.4,
        ('Bahamas Mix Cherem', 'Zebu Carnes Erick Silva'): 7.7,
        ('Bahamas Mix Cherem', 'Zebu Carnes Carlos Gomes'): 4.2,
        ('Bahamas Mix Cherem', 'Zebu Carnes Conceição das Alagoas'): 3.5,
        ('Bahamas Mix Cherem', 'Zebu Carnes Tônico dos Santos'): 2.9,
        ('Bahamas Mix Cherem', 'Zebu Carnes José Valim de Melo'): 2.1,
        ('Bahamas Mix Cherem', 'Mart Minas Parque Laranjeiras'): 6.8,
        ('Bahamas Mix Cherem', 'Mart Minas Olinda'): 6.8,
        ('Bahamas Mix Cherem', 'Mart Minas Santos Dumont'): 5,
        ('Bahamas Mix Cherem', 'Empório Bahamas Praça Uberaba'): 6,
        ('Bahamas Mix Cherem', 'Bahamas Mix Nossa Senhora do Desterro'): 7.1,
        ('Bahamas Mix Cherem', 'Bahamas Mix Santana Borges'): 11.3,
        ('Bahamas Mix Cherem', 'Bahamas Express Leopoldino'): 5.5,
        ('Bahamas Mix Cherem', 'Atacadão - Santos Dumont'): 5.3,
        ('Bahamas Mix Cherem', 'ABC Atacado e Varejo Cherém'): 2.2,
        ('Bahamas Mix Cherem', 'Supermercado ABC - Rua João Alfredo'): 3.4,
        ('Bahamas Mix Cherem', 'Villefort'): 3.8,
        ('Bahamas Express Leopoldino', 'Fazenda em Delta - MG'): 32.2,
        ('Bahamas Express Leopoldino', 'Zebu Carnes Ramid Mauad'): 7.1,
        ('Bahamas Express Leopoldino', 'Zebu Carnes Saudade'): 2.9,
        ('Bahamas Express Leopoldino', 'Zebu Carnes Nossa Senhora do Desterro'): 4.9,
        ('Bahamas Express Leopoldino', 'Zebu Carnes Governador Magalhães Pinto'): 2.1,
        ('Bahamas Express Leopoldino', 'Zebu Carnes Erick Silva'): 3.4,
        ('Bahamas Express Leopoldino', 'Zebu Carnes Carlos Gomes'): 1.7,
        ('Bahamas Express Leopoldino', 'Zebu Carnes Conceição das Alagoas'): 1.5,
        ('Bahamas Express Leopoldino', 'Zebu Carnes Tônico dos Santos'): 3.3,
        ('Bahamas Express Leopoldino', 'Zebu Carnes José Valim de Melo'): 5.6,
        ('Bahamas Express Leopoldino', 'Mart Minas Parque Laranjeiras'): 6.5,
        ('Bahamas Express Leopoldino', 'Mart Minas Olinda'): 4.7,
        ('Bahamas Express Leopoldino', 'Mart Minas Santos Dumont'): 1.9,
        ('Bahamas Express Leopoldino', 'Empório Bahamas Praça Uberaba'): 1.8,
        ('Bahamas Express Leopoldino', 'Bahamas Mix Nossa Senhora do Desterro'): 5.9,
        ('Bahamas Express Leopoldino', 'Bahamas Mix Santana Borges'): 5.4,
        ('Bahamas Express Leopoldino', 'Bahamas Mix Cherem'): 5.5,
        ('Bahamas Express Leopoldino', 'Atacadão - Santos Dumont'): 2.6,
        ('Bahamas Express Leopoldino', 'ABC Atacado e Varejo Cherém'): 3.7,
        ('Bahamas Express Leopoldino', 'Supermercado ABC - Rua João Alfredo'): 1.8,
        ('Bahamas Express Leopoldino', 'Villefort'): 3.1,
        ('Atacadão - Santos Dumont', 'Fazenda em Delta - MG'): 33.7,
        ('Atacadão - Santos Dumont', 'Zebu Carnes Ramid Mauad'): 6.3,
        ('Atacadão - Santos Dumont', 'Zebu Carnes Saudade'): 3.5,
        ('Atacadão - Santos Dumont', 'Zebu Carnes Nossa Senhora do Desterro'): 6.8,
        ('Atacadão - Santos Dumont', 'Zebu Carnes Governador Magalhães Pinto'): 3.5,
        ('Atacadão - Santos Dumont', 'Zebu Carnes Erick Silva'): 5.3,
        ('Atacadão - Santos Dumont', 'Zebu Carnes Carlos Gomes'): 3.6,
        ('Atacadão - Santos Dumont', 'Zebu Carnes Conceição das Alagoas'): 1.6,
        ('Atacadão - Santos Dumont', 'Zebu Carnes Tônico dos Santos'): 3.3,
        ('Atacadão - Santos Dumont', 'Zebu Carnes José Valim de Melo'): 6.5,
        ('Atacadão - Santos Dumont', 'Mart Minas Parque Laranjeiras'): 5.4,
        ('Atacadão - Santos Dumont', 'Mart Minas Olinda'): 3.7,
        ('Atacadão - Santos Dumont', 'Mart Minas Santos Dumont'): 0.8,
        ('Atacadão - Santos Dumont', 'Empório Bahamas Praça Uberaba'): 3,
        ('Atacadão - Santos Dumont', 'Bahamas Mix Nossa Senhora do Desterro'): 7.8,
        ('Atacadão - Santos Dumont', 'Bahamas Mix Santana Borges'): 4.7,
        ('Atacadão - Santos Dumont', 'Bahamas Mix Cherem'): 5.3,
        ('Atacadão - Santos Dumont', 'Bahamas Express Leopoldino'): 2.6,
        ('Atacadão - Santos Dumont', 'ABC Atacado e Varejo Cherém'): 3.8,
        ('Atacadão - Santos Dumont', 'Supermercado ABC - Rua João Alfredo'): 4.4,
        ('Atacadão - Santos Dumont', 'Villefort'): 1.4,
        ('ABC Atacado e Varejo Cherém', 'Fazenda em Delta - MG'): 29.9,
        ('ABC Atacado e Varejo Cherém', 'Zebu Carnes Ramid Mauad'): 8.6,
        ('ABC Atacado e Varejo Cherém', 'Zebu Carnes Saudade'): 6.4,
        ('ABC Atacado e Varejo Cherém', 'Zebu Carnes Nossa Senhora do Desterro'): 5.5,
        ('ABC Atacado e Varejo Cherém', 'Zebu Carnes Governador Magalhães Pinto'): 5.8,
        ('ABC Atacado e Varejo Cherém', 'Zebu Carnes Erick Silva'): 7.1,
        ('ABC Atacado e Varejo Cherém', 'Zebu Carnes Carlos Gomes'): 4.7,
        ('ABC Atacado e Varejo Cherém', 'Zebu Carnes Conceição das Alagoas'): 2.9,
        ('ABC Atacado e Varejo Cherém', 'Zebu Carnes Tônico dos Santos'): 1.5,
        ('ABC Atacado e Varejo Cherém', 'Zebu Carnes José Valim de Melo'): 3,
        ('ABC Atacado e Varejo Cherém', 'Mart Minas Parque Laranjeiras'): 5.5,
        ('ABC Atacado e Varejo Cherém', 'Mart Minas Olinda'): 5.5,
        ('ABC Atacado e Varejo Cherém', 'Mart Minas Santos Dumont'): 3.6,
        ('ABC Atacado e Varejo Cherém', 'Empório Bahamas Praça Uberaba'): 5.5,
        ('ABC Atacado e Varejo Cherém', 'Bahamas Mix Nossa Senhora do Desterro'): 6.5,
        ('ABC Atacado e Varejo Cherém', 'Bahamas Mix Santana Borges'): 6.2,
        ('ABC Atacado e Varejo Cherém', 'Bahamas Mix Cherem'): 2.2,
        ('ABC Atacado e Varejo Cherém', 'Bahamas Express Leopoldino'): 3.7,
        ('ABC Atacado e Varejo Cherém', 'Atacadão - Santos Dumont'): 3.8,
        ('ABC Atacado e Varejo Cherém', 'Supermercado ABC - Rua João Alfredo'): 3.5,
        ('ABC Atacado e Varejo Cherém', 'Villefort'): 2.6,
        ('Supermercado ABC - Rua João Alfredo', 'Fazenda em Delta - MG'): 30.4,
        ('Supermercado ABC - Rua João Alfredo', 'Zebu Carnes Ramid Mauad'): 8.9,
        ('Supermercado ABC - Rua João Alfredo', 'Zebu Carnes Saudade'): 4.7,
        ('Supermercado ABC - Rua João Alfredo', 'Zebu Carnes Nossa Senhora do Desterro'): 3,
        ('Supermercado ABC - Rua João Alfredo', 'Zebu Carnes Governador Magalhães Pinto'): 3.9,
        ('Supermercado ABC - Rua João Alfredo', 'Zebu Carnes Erick Silva'): 4.3,
        ('Supermercado ABC - Rua João Alfredo', 'Zebu Carnes Carlos Gomes'): 1.2,
        ('Supermercado ABC - Rua João Alfredo', 'Zebu Carnes Conceição das Alagoas'): 3,
        ('Supermercado ABC - Rua João Alfredo', 'Zebu Carnes Tônico dos Santos'): 4.6,
        ('Supermercado ABC - Rua João Alfredo', 'Zebu Carnes José Valim de Melo'): 3.8,
        ('Supermercado ABC - Rua João Alfredo', 'Mart Minas Parque Laranjeiras'): 9,
        ('Supermercado ABC - Rua João Alfredo', 'Mart Minas Olinda'): 6.5,
        ('Supermercado ABC - Rua João Alfredo', 'Mart Minas Santos Dumont'): 3.7,
        ('Supermercado ABC - Rua João Alfredo', 'Empório Bahamas Praça Uberaba'): 3.6,
        ('Supermercado ABC - Rua João Alfredo', 'Bahamas Mix Nossa Senhora do Desterro'): 4.1,
        ('Supermercado ABC - Rua João Alfredo', 'Bahamas Mix Santana Borges'): 7.2,
        ('Supermercado ABC - Rua João Alfredo', 'Bahamas Mix Cherem'): 3.4,
        ('Supermercado ABC - Rua João Alfredo', 'Bahamas Express Leopoldino'): 1.8,
        ('Supermercado ABC - Rua João Alfredo', 'Atacadão - Santos Dumont'): 4.4,
        ('Supermercado ABC - Rua João Alfredo', 'ABC Atacado e Varejo Cherém'): 3.5,
        ('Supermercado ABC - Rua João Alfredo', 'Villefort'): 3.8,
        ('Villefort', 'Fazenda em Delta - MG'): 32.2,
        ('Villefort', 'Zebu Carnes Ramid Mauad'): 6.6,
        ('Villefort', 'Zebu Carnes Saudade'): 3.7,
        ('Villefort', 'Zebu Carnes Nossa Senhora do Desterro'): 7.6,
        ('Villefort', 'Zebu Carnes Governador Magalhães Pinto'): 4.4,
        ('Villefort', 'Zebu Carnes Erick Silva'): 6.2,
        ('Villefort', 'Zebu Carnes Carlos Gomes'): 4.1,
        ('Villefort', 'Zebu Carnes Conceição das Alagoas'): 1.3,
        ('Villefort', 'Zebu Carnes Tônico dos Santos'): 1.7,
        ('Villefort', 'Zebu Carnes José Valim de Melo'): 5,
        ('Villefort', 'Mart Minas Parque Laranjeiras'): 4.1,
        ('Villefort', 'Mart Minas Olinda'): 3.3,
        ('Villefort', 'Mart Minas Santos Dumont'): 1.3,
        ('Villefort', 'Empório Bahamas Praça Uberaba'): 4,
        ('Villefort', 'Bahamas Mix Nossa Senhora do Desterro'): 7.9,
        ('Villefort', 'Bahamas Mix Santana Borges'): 4.1,
        ('Villefort', 'Bahamas Mix Cherem'): 3.8,
        ('Villefort', 'Bahamas Express Leopoldino'): 3.1,
        ('Villefort', 'Atacadão - Santos Dumont'): 1.4,
        ('Villefort', 'ABC Atacado e Varejo Cherém'): 2.6,
        ('Villefort', 'Supermercado ABC - Rua João Alfredo'): 3.8
    }
    return distances[(origin, destination)]
